### ISSUE TITLE
DO NOT update to 05.65.10

### ISSUE THREAD

**Issue by fawzib** [webosbrew/webos-homebrew-channel#121]
my 5 year old oled just received an update after many many years of neglect. LG is awake just to patch this exploit.

**Comment by tomasz-c** [comment]
Can you write if you checked it?
In the sense, did you do an update and the exploit stopped working?

**Comment by fawzib** [comment]
the exact same update was done on my c1 and it stopped working. not risking
and trying it on my 2016 oled.

**Comment by mpeter50** [comment]
tomasz was asking because what you have written is not clear. What is not working?
Is it your TV that is not working?
Or it works, but the homebrew channel app disappeared?
Or that and also you are not able to install it back again?

Please answer all questions above.
From what you have written, it is not clear whether you tried reinstalling the app.

**Comment by reimerp** [comment]
FYI: Same here: today LG awake to upgrade my 5y old UJ6309 from 06.00.20 to ...25 after years of ignoring this model.
Even option "automatically upgrade" was unchecked, there was a warning displayed from Homebrew to reboot since a crash happened. Just pressed "cancel" here, but don't know if this will re-appear. Don't know yet if I should upgrade (how) or not.

**Comment by jospezial** [comment]
See also #112

**Comment by fawzi-kyndryl** [comment]
your version is 5.60.20.01 and not the version in question. never update your lg tv after they ghosted you for years. this new update wont fix anything or add any feature. the whole update is to only remove the ability to install homebrew

**Comment by Soliver84** [comment]
I can now install 5.70.30 in dev mode? does anyone have it?

**Comment by Informatic** [comment]
Unrelated to Homebrew Channel. We have **always** advised people **not** to perform any software updates.
