### ISSUE TITLE
Homebrew Channel disappeared

### ISSUE THREAD

**Issue by NipponBill** [webosbrew/webos-homebrew-channel#160]
I have been using the Homebrew Channel for a few years now. I have never updated my TV that I know of. After rebooting the TV the entire Homebrew channel is completely gone.

I tried reapplying the RootMy.TV which appears to be successful, but there is no Homebrew Channel any longer.

**About this TV**

- Software version **05.70.35**
- Allow Automatic Updates = **off**
- TV Information **[LG] webOS TV UH7500**

Should I reset the TV? Can I restore the Homebrew Channel?

**Comment by throwaway96** [comment]
You must have updated, since 05.70.35 is the latest version for W16P (Realtek K2Lp) and W16R (MStar M2) and was released in late 2022/early 2023. I'm not able to determine what SoC you would have based on that partial model number (seems like it might be LX M16?).

Anyway, all your developer mode/homebrew stuff was probably wiped after the update when the modified `start-devmode.sh` was detected. Your firmware is not vulnerable to RootMyTV, and LG has blocked firmware downgrades. Currently, the only reliable option for rooting webOS 3.0 is [modifying NVM](https://gist.github.com/throwaway96/827ff726981cc2cbc46a22a2ad7337a1). GetMeIn *may* work (probably not though), but the binary on XDA runs a bunch of commands that will just cause problems. If you want to try it anyway, see the [OpenLGTV Discord](https://discord.gg/xWqRVEm) for a modified version that won't run unwanted commands.
