### ISSUE TITLE
Please add to your application the ability to install my ipk - dstore

### ISSUE THREAD

**Issue by Izvekov** [webosbrew/webos-homebrew-channel#56]
Please add to your application the ability to install my ipk - unofficial app store for LG (Russia) - Dstore. The package is located http://msx.lh1.in/ipk/dstorevip.ipk
Logo http://webosapp.club/images/dstore.png

**Comment by DavidBuchanan314** [comment]
The rules for inclusion in the default repo are still under discussion, here: https://github.com/webosbrew/apps-repo/issues/6

One rule is very certain - piracy services are not allowed. Unless I'm mistaken, Dstore links to at least one pirate movie streaming service.

**Comment by mariotaku** [comment]
@Izvekov A side note: We don't index possible copyright related app is because that may come with legal liability. If you understand the possible risk, you can make your own repo by refer to this repo: https://github.com/webosbrew/apps-repo . If you got your own repo setup, you can let user to add this repo to hbchannel app on their own.

**Comment by Informatic** [comment]
Sidenote: multi-repo support is still WIP at #50 - contributions appreciated.
