### ISSUE TITLE
What is the correct way to uninstall your app from TV?

### ISSUE THREAD

**Issue by Izvekov** [webosbrew/webos-homebrew-channel#57]
What is the correct way to uninstall your app from TV? Removed by standard means - now problems. I get root, the TV reboots, I go telnet, everything seems to be fine, I give reboot - reboot and there is no tenlet access. Problem.

**Comment by Informatic** [comment]
I am not entirely sure what is the starting point here, what is the outcome, and what is your expected outcome?

If the issue is that after removal of Homebrew Channel you still have root telnetd exposed, then you can alleviate that by just removing the startup script at `/media/cryptofs/apps/usr/palm/services/com.palmdts.devmode.service/start-devmode.sh`. All paths that are related to Homebrew Channel and rooting are listed here: https://github.com/webosbrew/webos-homebrew-channel/issues/11
