### ISSUE TITLE
erorr installing 

### ISSUE THREAD

**Issue by SuperPi911** [webosbrew/webos-homebrew-channel#61]
ares-install --device tv /home/rares/Downloads/org.webosbrew.hbchannel_0.2.1_all.ipk 
ares-install ERR! Error: connect ECONNREFUSED 192.168.1.104:22

**Comment by NguyenASang** [comment]
You can install it using IDE. I get that error while using command but when I using IDE, I didn't get that error anymore

**Comment by Informatic** [comment]
Error above is caused by misconfigured webOS SDK.

See: https://github.com/webosbrew/webos-homebrew-channel#development-tv-setup

If your TV is already rooted - you need to enable SSH Server in Homebrew Channel settings.
If your TV is not rooted - you need to use port `9922` and apropriate ssh key downloaded from developer mode app key server.
