### ISSUE TITLE
suddenly the repo cannot load

### ISSUE THREAD

**Issue by spants** [webosbrew/webos-homebrew-channel#62]
On the latest version - it was working fine and now I get an error loading repo message..... Tried reinstalling.

**Comment by DavidBuchanan314** [comment]
This is the same underlying issue as https://github.com/RootMyTV/RootMyTV.github.io/issues/9 (LG broke SSL)

**Comment by cpetry** [comment]
I also have this problem

**Comment by Informatic** [comment]
This should be fixed now, webosbrew repo is now hosted behind cloudflare with their own certificates.

**Comment by Soukyuu** [comment]
I am still having this issue, both homebrew channel failing to load repo and rootmy.tv complaining about SSL. I am on 6.00.25, 55B7D device. Is there any steps I can rake besides fully resetting my TV?

**Comment by throwaway96** [comment]
W17H (M16P) firmware 06.00.25 (webOS 3.9.0) is vulnerable to RootMyTV v1 and v2, so if you can get past the SSL issue it should work.

You can host RootMyTV on a local HTTP server (e.g., I've used `python3 -m http.server`) and then navigate to your local instance in the TV's browser. You could also use your PC's browser to view `index.html` locally (`file:`) and [supply your TV's IP address](https://github.com/RootMyTV/RootMyTV.github.io/blob/main/index.html#L266) (although I've never done that myself). By default it will try to get `stage2.html` from `https://rootmy.tv`, but you can edit [the URL](https://github.com/RootMyTV/RootMyTV.github.io/blob/main/index.html#L49) in `index.html`.

I believe `com.webos.app.facebooklogin` requires `stage2.html` to be served over HTTPS, but it's *possible* it uses a different cert store than the browser. You can change the priorities of the apps ([`com.webos.app.acrcard`](https://github.com/RootMyTV/RootMyTV.github.io/blob/main/index.html#L190), [`com.webos.app.facebooklogin`](https://github.com/RootMyTV/RootMyTV.github.io/blob/main/index.html#L185), [`com.webos.app.alibaba`](https://github.com/RootMyTV/RootMyTV.github.io/blob/main/index.html#L190)) so that a different one gets chosen. `acrcard` is apparently [broken on 3.x](https://github.com/RootMyTV/RootMyTV.github.io/blob/main/index.html#L189), but it still may be worth a try. I do not believe `alibaba` is present on W17H.

Much of `index.html` is devoted to working around origin issues and establishing an SSAP connection. Instead of using it, you can also just connect to the TV using an [SSAP client](https://github.com/throwaway96/webos-ssap-web) and send the [SSAP request](https://github.com/RootMyTV/RootMyTV.github.io/blob/main/index.html#L212-L215) manually. The endpoint is always `ssap://system.launcher/launch`, and the payload will be:
```json
{
"id":"<target app>",
"params":{"<param name>":"<stage2 URL>"}
}
```
Each target app has its own parameter name:
* `com.webos.app.facebooklogin`: `server`
* `com.webos.app.acrcard`: `contentTarget`
* `com.webos.app.alibaba`: `target`
You can either try to use the RootMyTV hosted `stage2.html` URL (`https://rootmy.tv/stage2.html`) or host it yourself.
