### ISSUE TITLE
Dropbear ssh not working

### ISSUE THREAD

**Issue by PabloGirol** [webosbrew/webos-homebrew-channel#84]
I rooted my tv months ago, and couldnt do anything with it really, there is no actually much homebrew going on...
Recently saw this homebrew channel, installed it (manually) and noticed that ssh is not working anymore, diagnosing it saw that the dropbear daemon can't be executed in my tv at all, this is the error:

```
/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service/bin # ./dropbear 
./dropbear: /lib/libc.so.6: version `GLIBC_2.15' not found (required by ./dropbear)
./dropbear: /lib/libc.so.6: version `GLIBC_2.17' not found (required by ./dropbear)
```

My tv has a really ancient version of WebOs 1.4.0 IIRC that only works with the GetMeIn exploit

Output of uname -a
`Linux LGSmartTV 3.10.19-32.afro.6 #1 SMP PREEMPT Fri Jun 28 03:44:13 UTC 2019 armv7l GNU/Linux`

libc.so.6 --version output:
![imagen](https://user-images.githubusercontent.com/47150336/151410345-2aa821ac-1092-4280-9e6b-674de1e58b87.png)

So what Im really asking is, how can I compile dropbear for this device, or get a binary specific for this one at least?
Help would be much apreciated

**Comment by Informatic** [comment]
Nice catch!

All the binaries we use are built using this script:
https://github.com/webosbrew/webos-homebrew-channel/blob/main/tools/build-binaries.sh

The issue is that [our current NDK](https://github.com/webosbrew/meta-lg-webos-ndk) (this script uses) is based on glibc from ~webOS 4.x era. While this is not an issue on 3.x, this is problematic on 1.x of course.

Simultaneously we are working on remaking the NDK with much older dependencies to widen platform support - there's an experimental prebuilt NDK based on Buildroot that is targetting pre-webOS 1.x glibc and such: https://github.com/openlgtv/buildroot-nc4/releases/tag/webos-6e2e155 - you can probably try building dropbear using that and report if that works for you :)

**Comment by PabloGirol** [comment]
I can confirm this is working pretty good, dropbear is now working, but seems that I can't login as root where is the sshd_config file to enable it?

Also thank you for your help and fast response

**Comment by Informatic** [comment]
90% of dropbear config is set in buildtime. The fact you can't login as
root using default password (alpine) is likely caused by this:
https://github.com/webosbrew/webos-homebrew-channel/pull/79

I will go over the pending PRs over the weekend, and will try looking into
rebuilding binaries with that other NDK to include in main release as well.

**Comment by PabloGirol** [comment]
Seems like it, I now have uploaded a ssh key, I thought that PermitRootLogin was disabled in some way as the GetMeIn exploit enabled me to change root's password and to log in with it, again thank you.
